---
name: Pull request build

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint project
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Check for spelling mistakes
        uses: reviewdog/action-misspell@v1.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          reporter: github-pr-check
          level: error

      - name: Lint code base
        uses: github/super-linter@v4.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          LINTER_RULES_PATH: .
          FILTER_REGEX_EXCLUDE: /target/
          VALIDATE_EDITORCONFIG: true
          VALIDATE_JAVA: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_XML: true
          VALIDATE_YAML: true

  build:
    needs: lint
    runs-on: ubuntu-latest
    name: Build project
    env:
      CI_HEADLESS: true
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Cache maven repository
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Verify the project and create coverage report
        run: mvn clean verify jacoco:report -B -ff

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: coverage-report
          path: target/site/jacoco/jacoco.xml

  coverage:
    runs-on: ubuntu-latest
    name: Push coverage report to codecov
    needs: build
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Download coverage report from artifacts
        uses: actions/download-artifact@v2
        with:
          name: coverage-report

      - name: Push to codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: jacoco.xml
          flags: unit-tests
          name: hebcal-api-codecov
          fail_ci_if_error: true
