---
name: Pull request triage

on:
  pull_request_target:
    branches:
      - master
    types: [opened]

permissions:
  pull-requests: write

jobs:
  triage-non-dependabot:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    name: Triage non dependabot
    steps:
      - name: Add review label
        uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          labels: "status: needs review"

  triage-by-dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    name: Triage by dependabot
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add approved label
        uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          labels: "status: approved"
